name: Lint, Build, Test

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.13.2 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      - name: Install dependencies
        uses: cypress-io/github-action@v2
        with:
          # Just perform install
          runTests: false
      # Lint before testing
      - run: npm run lint
      # Run e2e
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # Already installed dependencies above
          install: false
          build: npm run build
          start: npm start:server
          config: baseUrl=http://localhost:1337
