name: PR Checks

on:
  pull_request:
    branches:
      - main
    # Defaults + ready_for_review to trigger a re-run when a Draft PR is converted to a normal PR
    # See: https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/17
    types: [opened, synchronize, reopened, ready_for_review]

# See: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  contents: read
  pull-requests: read

# Only allow one build per PR source branch to run at once, cancelling in-progress
# builds when new builds arrive
# See: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idconcurrency
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # Checks if the PR is in draft status and fails if so, which does 2 things:
  #  - Prevents the PR from being merged in that state
  #  - Prevents all downstream jobs from running
  # Additionally, require each test to pass before running the next to prevent
  # running unnecessary jobs if any upstream jobs already failed
  draft:
    name: "Check Draft Status"
    runs-on: ubuntu-latest
    steps:
      - name: "Fail draft PRs"
        if: github.event.pull_request.draft == true
        run: |
          echo "Skipping execution for draft PR"
          exit 1
      - run: echo "PR is not Draft"

  # Check Linting status
  lint:
    uses: ./.github/workflows/run-npm-script.yml
    needs: draft
    with:
      label: "Lint"
      script: "npm run lint"

  # Run Jest Unit Tests
  test-unit:
    uses: ./.github/workflows/run-npm-script.yml
    needs: lint
    with:
      label: "Test: Unit"
      script: "npm run test:unit"

  # Run Cypress End to End Tests
  test-e2e:
    name: "Test: End to End"
    runs-on: ubuntu-latest
    needs: test-unit
    # stop the job if it runs over 20 minutes to prevent a hanging process from eating minutes
    timeout-minutes: 45
    steps:
      # Checkout and node setup are shared in both `pr-actions.yml` and `run-npm-script.yml`
      # If you change one, please change the other
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"
          cache: 'npm'
      # https://github.com/cypress-io/github-action
      - uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
          config-file: cypress.config.js
          wait-on: 'http://localhost:1337'
          # wait for 2 minutes for the server to respond
          wait-on-timeout: 120
        env:
          # Never add vue devtools when running in GitHub
          # Mock a production config without setting NODE_ENV
          # so that Cypress runs the proper test suites
          # and Vue Devtools are not included
          CUTTLE_ENV: production
          VUE_APP_API_URL: http://localhost:1337
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
